<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\AccomplishedProject;

class AccomplishedProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'title' => 'Barangay Health Center Modernization Project',
                'description' => 'Complete renovation and modernization of the barangay health center to provide better healthcare services to residents. The project included new medical equipment, improved waiting areas, better facilities for healthcare workers, and a dedicated maternal and child care room.',
                'category' => 'Health',
                'location' => 'Barangay Hall Compound, Lower Malinao',
                'budget' => 2800000.00,
                'start_date' => '2023-03-15',
                'completion_date' => '2023-08-20',
                'status' => 'completed',
                'beneficiaries' => 'All residents of Lower Malinao (approximately 5,200 people)',
                'impact' => 'Improved healthcare access, reduced travel time to medical facilities, better emergency response capabilities, increased patient satisfaction from 65% to 92%',
                'funding_source' => 'Department of Health (DOH) - Health Facilities Enhancement Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => true,
            ],
            [
                'title' => 'Solar Street Lighting Project Phase 1',
                'description' => 'Installation of solar-powered street lights along major roads and pathways to improve safety and visibility during nighttime. This eco-friendly project promotes sustainable energy use and reduces electricity costs for the barangay.',
                'category' => 'Infrastructure',
                'location' => 'Main roads and pathways, Lower Malinao',
                'budget' => 1950000.00,
                'start_date' => '2023-01-10',
                'completion_date' => '2023-04-25',
                'status' => 'completed',
                'beneficiaries' => 'All residents, especially those who travel at night, motorists, and pedestrians',
                'impact' => 'Enhanced public safety, reduced crime incidents by 40%, improved community mobility at night, reduced electricity costs by ₱15,000 monthly',
                'funding_source' => 'Department of Energy (DOE) - Solar Street Lighting Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => true,
            ],
            [
                'title' => 'Computer Literacy Training Program for Senior Citizens',
                'description' => 'Comprehensive computer literacy training for senior citizens and unemployed youth. The program covered basic computer operations, internet usage, digital skills, and online banking to help bridge the digital divide.',
                'category' => 'Education',
                'location' => 'Barangay Multi-Purpose Hall, Lower Malinao',
                'budget' => 650000.00,
                'start_date' => '2023-06-01',
                'completion_date' => '2023-09-30',
                'status' => 'completed',
                'beneficiaries' => '180 residents (120 senior citizens and 60 unemployed youth)',
                'impact' => 'Improved digital literacy, better employment opportunities for youth, enhanced communication skills, increased confidence in using technology among seniors',
                'funding_source' => 'Department of Information and Communications Technology (DICT) - Digital Literacy Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => false,
            ],
            [
                'title' => 'Organic Farming Training and Support Program',
                'description' => 'Training program for farmers on organic farming techniques and sustainable agriculture practices. Included distribution of organic seeds, farming tools, and establishment of demonstration farms.',
                'category' => 'Agriculture',
                'location' => 'Agricultural areas of Lower Malinao (Purok 3, 4, and 7)',
                'budget' => 950000.00,
                'start_date' => '2023-02-01',
                'completion_date' => '2023-05-15',
                'status' => 'completed',
                'beneficiaries' => '65 local farmers and their families (approximately 325 people)',
                'impact' => 'Improved agricultural productivity by 35%, reduced chemical use by 60%, better food security, increased farmer income by ₱8,000 monthly',
                'funding_source' => 'Department of Agriculture (DA) - Organic Agriculture Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => false,
            ],
            [
                'title' => 'Waste Management and Segregation Program',
                'description' => 'Implementation of comprehensive waste management system including proper waste segregation, recycling initiatives, community awareness campaigns, and establishment of Materials Recovery Facility (MRF).',
                'category' => 'Environment',
                'location' => 'Entire barangay of Lower Malinao',
                'budget' => 750000.00,
                'start_date' => '2023-07-01',
                'completion_date' => '2023-10-31',
                'status' => 'completed',
                'beneficiaries' => 'All residents and the environment',
                'impact' => 'Cleaner environment, reduced pollution by 45%, improved public health, increased waste diversion rate to 65%, generated ₱25,000 monthly from recyclables',
                'funding_source' => 'Department of Environment and Natural Resources (DENR) - Solid Waste Management Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => true,
            ],
            [
                'title' => 'Senior Citizens Activity Center and Wellness Hub',
                'description' => 'Construction of a dedicated activity center for senior citizens with facilities for recreation, exercise, social activities, and medical monitoring. Includes exercise equipment, medical monitoring devices, and multipurpose rooms.',
                'category' => 'Social Services',
                'location' => 'Barangay Hall Compound, Lower Malinao',
                'budget' => 1450000.00,
                'start_date' => '2023-04-01',
                'completion_date' => '2023-07-15',
                'status' => 'completed',
                'beneficiaries' => 'Senior citizens of Lower Malinao (approximately 320 people)',
                'impact' => 'Improved quality of life for seniors, better social engagement, enhanced healthcare monitoring, reduced isolation among elderly, increased participation in barangay activities',
                'funding_source' => 'Department of Social Welfare and Development (DSWD) - Senior Citizens Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => false,
            ],
            [
                'title' => 'Youth Skills Development and Livelihood Program',
                'description' => 'Training program for out-of-school youth in various skills including carpentry, electrical work, plumbing, welding, and other technical skills for better employment opportunities and entrepreneurship.',
                'category' => 'Livelihood',
                'location' => 'Barangay Multi-Purpose Hall and Technical Training Center, Lower Malinao',
                'budget' => 880000.00,
                'start_date' => '2023-05-01',
                'completion_date' => '2023-08-31',
                'status' => 'completed',
                'beneficiaries' => '85 out-of-school youth (aged 18-25)',
                'impact' => 'Reduced unemployment by 65%, improved economic opportunities, enhanced community skills, 45 participants now employed, 15 started their own businesses',
                'funding_source' => 'Technical Education and Skills Development Authority (TESDA) - Skills Training Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => false,
            ],
            [
                'title' => 'Emergency Response Equipment and Communication System Upgrade',
                'description' => 'Upgrade of emergency response equipment including new fire extinguishers, first aid kits, emergency communication systems, and disaster preparedness training for better disaster response.',
                'category' => 'Infrastructure',
                'location' => 'Barangay Hall and strategic locations throughout Lower Malinao',
                'budget' => 520000.00,
                'start_date' => '2023-09-01',
                'completion_date' => '2023-11-30',
                'status' => 'completed',
                'beneficiaries' => 'All residents in emergency situations',
                'impact' => 'Improved disaster response time by 40%, enhanced public safety, better emergency preparedness, increased community confidence in emergency services',
                'funding_source' => 'Department of the Interior and Local Government (DILG) - Local Government Support Fund',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => false,
            ],
            [
                'title' => 'Barangay Water System Improvement Project',
                'description' => 'Upgrading and expansion of barangay water system to provide clean and potable water to all households. Includes new water tanks, distribution lines, and water quality monitoring.',
                'category' => 'Infrastructure',
                'location' => 'Entire barangay of Lower Malinao',
                'budget' => 3200000.00,
                'start_date' => '2023-11-01',
                'completion_date' => '2024-02-28',
                'status' => 'completed',
                'beneficiaries' => 'All 1,200 households in Lower Malinao',
                'impact' => 'Improved water quality, reduced water-borne diseases by 30%, increased water pressure, 24/7 water availability, reduced water costs for residents',
                'funding_source' => 'Local Water Utilities Administration (LWUA) - Water System Development Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => true,
            ],
            [
                'title' => 'Barangay Day Care Center Renovation',
                'description' => 'Complete renovation of the barangay day care center to provide better early childhood education facilities. Includes new furniture, educational materials, and improved learning environment.',
                'category' => 'Education',
                'location' => 'Barangay Hall Compound, Lower Malinao',
                'budget' => 680000.00,
                'start_date' => '2023-12-01',
                'completion_date' => '2024-01-31',
                'status' => 'completed',
                'beneficiaries' => 'Children aged 3-5 years old (approximately 45 children)',
                'impact' => 'Better early childhood education, improved learning environment, increased enrollment by 25%, better preparation for elementary school',
                'funding_source' => 'Department of Education (DepEd) - Early Childhood Care and Development Program',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => false,
            ],
        ];

        foreach ($projects as $project) {
            AccomplishedProject::create($project);
        }
    }
} 