<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\AccomplishedProject;

class AccomplishedProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            // Projects (with budget)
            [
                'type' => 'project',
                'title' => 'Barangay Health Center Modernization',
                'description' => 'Renovation of the health center with new equipment, triage area, and mother-and-child room.',
                'category' => 'Health',
                'location' => 'Barangay Hall Compound, Lower Malinao',
                'budget' => 2800000.00,
                'start_date' => '2023-03-15',
                'completion_date' => '2023-08-20',
                'status' => 'completed',
                'beneficiaries' => 'All residents of Lower Malinao (~5,200 people)',
                'impact' => 'Improved healthcare access and faster emergency response.',
                'funding_source' => 'DOH - HFEP',
                'implementing_agency' => 'Barangay Council of Lower Malinao',
                'is_featured' => true,
                'image' => 'uploads/projects/health-center-modernization.jpg',
            ],
            [
                'type' => 'project',
                'title' => 'Solar-Powered Streetlighting Phase 1',
                'description' => 'Installation of 60 solar streetlights along main thoroughfares to improve night-time safety.',
                'category' => 'Infrastructure',
                'location' => 'Purok 1 to Purok 4, Lower Malinao',
                'budget' => 1450000.00,
                'start_date' => '2024-01-10',
                'completion_date' => '2024-03-18',
                'status' => 'completed',
                'beneficiaries' => 'Commuters and households along the covered puroks',
                'impact' => 'Reduced accidents and crime incidents reported at night.',
                'funding_source' => 'Barangay Development Fund',
                'implementing_agency' => 'Barangay Engineering Office',
                'is_featured' => false,
                'image' => 'uploads/projects/solar-streetlights.jpg',
            ],
            [
                'type' => 'project',
                'title' => 'Purok 5 Drainage Rehabilitation',
                'description' => 'Upgrading 350 meters of drainage with concrete lining and catch basins to mitigate flooding.',
                'category' => 'Infrastructure',
                'location' => 'Purok 5, Lower Malinao',
                'budget' => 980000.00,
                'start_date' => '2024-06-01',
                'completion_date' => '2024-08-12',
                'status' => 'completed',
                'beneficiaries' => '215 households affected by seasonal flooding',
                'impact' => 'Fewer flood incidents and reduced property damage during heavy rains.',
                'funding_source' => 'Calamity Fund',
                'implementing_agency' => 'Municipal Engineering Office',
                'is_featured' => false,
                'image' => 'uploads/projects/drainage-rehab.jpg',
            ],
            [
                'type' => 'project',
                'title' => 'Barangay Multipurpose Hall Upgrade',
                'description' => 'Refurbishment of multipurpose hall with acoustic treatment, seating, and ventilation improvements.',
                'category' => 'Social Services',
                'location' => 'Barangay Hall, Lower Malinao',
                'budget' => 750000.00,
                'start_date' => '2024-09-10',
                'completion_date' => '2024-11-05',
                'status' => 'completed',
                'beneficiaries' => 'Community groups and barangay assemblies',
                'impact' => 'Better venue for public hearings, trainings, and relief operations staging.',
                'funding_source' => 'Local Government Support Fund',
                'implementing_agency' => 'Barangay Council',
                'is_featured' => false,
                'image' => 'uploads/projects/multipurpose-upgrade.jpg',
            ],
            [
                'type' => 'project',
                'title' => 'Early Childhood Development Center',
                'description' => 'Construction of a daycare classroom with play area and sanitation facilities.',
                'category' => 'Education',
                'location' => 'Purok 7, Lower Malinao',
                'budget' => 1200000.00,
                'start_date' => '2024-02-20',
                'completion_date' => '2024-06-30',
                'status' => 'completed',
                'beneficiaries' => 'Preschool-aged children and parents in Purok 6-7',
                'impact' => 'Increased enrollment in ECCD and improved learning environment.',
                'funding_source' => 'National ECCD Program',
                'implementing_agency' => 'Barangay Social Services Committee',
                'is_featured' => true,
                'image' => 'uploads/projects/eccd-center.jpg',
            ],

            // Activities (no budget field)
            [
                'type' => 'activity',
                'title' => 'Coastal Clean-Up and Mangrove Planting',
                'description' => 'Community clean-up and planting of 500 mangrove seedlings to improve shoreline protection.',
                'category' => 'Environment',
                'location' => 'Coastal Area, Lower Malinao',
                'start_date' => '2023-09-05',
                'completion_date' => '2023-09-05',
                'status' => 'completed',
                'beneficiaries' => 'Coastal households and fisherfolk',
                'impact' => 'Cleaner shoreline and better fish nursery habitats.',
                'funding_source' => 'Local Environmental Protection Fund',
                'implementing_agency' => 'Barangay Environmental Council',
                'is_featured' => false,
                'image' => 'uploads/projects/coastal-cleanup.jpg',
            ],
            [
                'type' => 'activity',
                'title' => 'Dengue Prevention House-to-House Drive',
                'description' => 'Inspection of households, distribution of larvicides, and IEC on dengue prevention.',
                'category' => 'Health',
                'location' => 'Purok 1-8, Lower Malinao',
                'start_date' => '2024-04-12',
                'completion_date' => '2024-04-13',
                'status' => 'completed',
                'beneficiaries' => 'Households visited during the campaign',
                'impact' => 'Reduced reported breeding sites and higher community awareness.',
                'funding_source' => 'Barangay Health Fund',
                'implementing_agency' => 'Barangay Health Office',
                'is_featured' => true,
                'image' => 'uploads/projects/dengue-drive.jpg',
            ],
            [
                'type' => 'activity',
                'title' => 'Nutrition Month Feeding Program',
                'description' => 'Daily feeding for underweight children with nutrition education for parents.',
                'category' => 'Health',
                'location' => 'Barangay Multipurpose Hall',
                'start_date' => '2024-07-01',
                'completion_date' => '2024-07-31',
                'status' => 'completed',
                'beneficiaries' => 'Underweight children aged 3-8',
                'impact' => 'Weight gain among beneficiaries and improved nutrition practices at home.',
                'funding_source' => 'Barangay Nutrition Program',
                'implementing_agency' => 'Barangay Nutrition Committee',
                'is_featured' => false,
                'image' => 'uploads/projects/nutrition-month.jpg',
            ],
            [
                'type' => 'activity',
                'title' => 'Disaster Preparedness Training',
                'description' => 'Workshop on basic life support, evacuation drills, and household emergency kits.',
                'category' => 'Public Safety',
                'location' => 'Barangay Gym, Lower Malinao',
                'start_date' => '2024-05-18',
                'completion_date' => '2024-05-18',
                'status' => 'completed',
                'beneficiaries' => 'Community volunteers and barangay responders',
                'impact' => 'Higher readiness scores in post-training evaluations.',
                'funding_source' => 'Local DRRM Fund',
                'implementing_agency' => 'Barangay DRRM Council',
                'is_featured' => false,
                'image' => 'uploads/projects/drill-training.jpg',
            ],
            [
                'type' => 'activity',
                'title' => 'Skills Training: Backyard Vegetable Gardening',
                'description' => 'Hands-on training on container gardening, composting, and seed distribution.',
                'category' => 'Livelihood',
                'location' => 'Purok 6 Covered Court',
                'start_date' => '2024-08-22',
                'completion_date' => '2024-08-22',
                'status' => 'completed',
                'beneficiaries' => 'Households interested in food security initiatives',
                'impact' => 'More households started vegetable plots and reduced market spend.',
                'funding_source' => 'Barangay Livelihood Fund',
                'implementing_agency' => 'Barangay Agriculture Committee',
                'is_featured' => false,
                'image' => 'uploads/projects/gardening-training.jpg',
            ],
        ];

        foreach ($projects as $project) {
            AccomplishedProject::create($project);
        }
    }
} 