<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Residents;
use Carbon\Carbon;

class ResidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Senior Citizen - Low Income
        Residents::create([
            'first_name' => 'Remedios',
            'middle_name' => 'Santos',
            'last_name' => 'Dela Cruz',
            'suffix' => null,
            'email' => 'remedios.santos@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 1, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09191234567',
            'birth_date' => Carbon::now()->subYears(72),
            'marital_status' => 'Widowed',
            'occupation' => 'Housewife',
            'age' => 72,
            'family_size' => 3,
            'education_level' => 'Elementary',
            'income_level' => 'Low',
            'employment_status' => 'Unemployed',
            'is_pwd' => true,
            'active' => true,
        ]);

        // Young Professional - Middle Income
        Residents::create([
            'first_name' => 'Juan Carlos',
            'middle_name' => 'Dela Cruz',
            'last_name' => 'Santos',
            'suffix' => null,
            'email' => 'juan.santos@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 2, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => '09191234569',
            'birth_date' => Carbon::now()->subYears(29),
            'marital_status' => 'Single',
            'occupation' => 'Private Employee',
            'age' => 29,
            'family_size' => 4,
            'education_level' => 'College',
            'income_level' => 'Middle',
            'employment_status' => 'Full-time',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Unemployed Youth - Low Income
        Residents::create([
            'first_name' => 'Ana Patricia',
            'middle_name' => 'Reyes',
            'last_name' => 'Cruz',
            'suffix' => null,
            'email' => 'ana.reyes@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 3, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09191234571',
            'birth_date' => Carbon::now()->subYears(21),
            'marital_status' => 'Single',
            'occupation' => 'Student',
            'age' => 21,
            'family_size' => 5,
            'education_level' => 'High School',
            'income_level' => 'Low',
            'employment_status' => 'Unemployed',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Self-employed Entrepreneur - Upper Middle Income
        Residents::create([
            'first_name' => 'Pedro Antonio',
            'middle_name' => 'Martinez',
            'last_name' => 'Flores',
            'suffix' => null,
            'email' => 'pedro.martinez@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 4, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => '09191234573',
            'birth_date' => Carbon::now()->subYears(47),
            'marital_status' => 'Married',
            'occupation' => 'Vendor',
            'age' => 47,
            'family_size' => 6,
            'education_level' => 'Vocational',
            'income_level' => 'Upper Middle',
            'employment_status' => 'Self-employed',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Part-time Worker - Lower Middle Income
        Residents::create([
            'first_name' => 'Luz Maria',
            'middle_name' => 'Garcia',
            'last_name' => 'Santos',
            'suffix' => null,
            'email' => 'luz.garcia@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 5, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09191234575',
            'birth_date' => Carbon::now()->subYears(38),
            'marital_status' => 'Married',
            'occupation' => 'Teacher',
            'age' => 38,
            'family_size' => 4,
            'education_level' => 'High School',
            'income_level' => 'Lower Middle',
            'employment_status' => 'Part-time',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // High-income Professional
        Residents::create([
            'first_name' => 'Carlos Miguel',
            'middle_name' => 'Lopez',
            'last_name' => 'Gonzales',
            'suffix' => null,
            'email' => 'carlos.lopez@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 6, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => '09191234577',
            'birth_date' => Carbon::now()->subYears(54),
            'marital_status' => 'Married',
            'occupation' => 'Government Employee',
            'age' => 54,
            'family_size' => 5,
            'education_level' => 'Post Graduate',
            'income_level' => 'High',
            'employment_status' => 'Full-time',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Middle-aged Parent - Middle Income
        Residents::create([
            'first_name' => 'Sofia Isabel',
            'middle_name' => 'Rodriguez',
            'last_name' => 'Torres',
            'suffix' => null,
            'email' => 'sofia.rodriguez@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 7, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09191234579',
            'birth_date' => Carbon::now()->subYears(42),
            'marital_status' => 'Married',
            'occupation' => 'Private Employee',
            'age' => 42,
            'family_size' => 6,
            'education_level' => 'College',
            'income_level' => 'Middle',
            'employment_status' => 'Full-time',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Young Parent - Lower Middle Income
        Residents::create([
            'first_name' => 'Rafael Jose',
            'middle_name' => 'Hernandez',
            'last_name' => 'Cruz',
            'suffix' => null,
            'email' => 'rafael.hernandez@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 1, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => '09191234581',
            'birth_date' => Carbon::now()->subYears(26),
            'marital_status' => 'Married',
            'occupation' => 'Construction Worker',
            'age' => 26,
            'family_size' => 3,
            'education_level' => 'High School',
            'income_level' => 'Lower Middle',
            'employment_status' => 'Full-time',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Senior Professional - Upper Middle Income
        Residents::create([
            'first_name' => 'Elena Maria',
            'middle_name' => 'Santos',
            'last_name' => 'Reyes',
            'suffix' => null,
            'email' => 'elena.santos@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 2, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09191234583',
            'birth_date' => Carbon::now()->subYears(58),
            'marital_status' => 'Widowed',
            'occupation' => 'Teacher',
            'age' => 58,
            'family_size' => 2,
            'education_level' => 'Post Graduate',
            'income_level' => 'Upper Middle',
            'employment_status' => 'Full-time',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Young Adult - Low Income
        Residents::create([
            'first_name' => 'Roderick',
            'middle_name' => 'Palacay',
            'last_name' => 'Tajos',
            'suffix' => null,
            'email' => 'rodericktajos02@gmail.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 3, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => '09123456789',
            'birth_date' => Carbon::now()->subYears(19),
            'marital_status' => 'Single',
            'occupation' => 'Student',
            'age' => 19,
            'family_size' => 4,
            'education_level' => 'High School',
            'income_level' => 'Low',
            'employment_status' => 'Unemployed',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Divorced Parent - Lower Middle Income
        Residents::create([
            'first_name' => 'Maricel Ann',
            'middle_name' => 'Villanueva',
            'last_name' => 'Torres',
            'suffix' => null,
            'email' => 'maricel.villanueva@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 4, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09191234587',
            'birth_date' => Carbon::now()->subYears(35),
            'marital_status' => 'Divorced',
            'occupation' => 'Vendor',
            'age' => 35,
            'family_size' => 3,
            'education_level' => 'High School',
            'income_level' => 'Lower Middle',
            'employment_status' => 'Full-time',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Separated Individual - Low Income
        Residents::create([
            'first_name' => 'Roberto Manuel',
            'middle_name' => 'Alcantara',
            'last_name' => 'Ramos',
            'suffix' => null,
            'email' => 'roberto.alcantara@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 5, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => '09191234589',
            'birth_date' => Carbon::now()->subYears(44),
            'marital_status' => 'Separated',
            'occupation' => 'Private Employee',
            'age' => 44,
            'family_size' => 2,
            'education_level' => 'Elementary',
            'income_level' => 'Low',
            'employment_status' => 'Full-time',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // No Education - Low Income
        Residents::create([
            'first_name' => 'Teresa',
            'middle_name' => 'Bautista',
            'last_name' => 'Morales',
            'suffix' => null,
            'email' => 'teresa.bautista@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 6, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09191234591',
            'birth_date' => Carbon::now()->subYears(68),
            'marital_status' => 'Widowed',
            'occupation' => 'Housewife',
            'age' => 68,
            'family_size' => 4,
            'education_level' => 'No Education',
            'income_level' => 'Low',
            'employment_status' => 'Part-time',
            'is_pwd' => true,
            'active' => true,
        ]);

        // Critical Health Status - Low Income
        Residents::create([
            'first_name' => 'Eduardo',
            'middle_name' => 'Santos',
            'last_name' => 'Dela Rosa',
            'suffix' => null,
            'email' => 'eduardo.santos@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 7, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => '09191234593',
            'birth_date' => Carbon::now()->subYears(75),
            'marital_status' => 'Widowed',
            'occupation' => 'Housewife',
            'age' => 75,
            'family_size' => 2,
            'education_level' => 'Elementary',
            'income_level' => 'Low',
            'employment_status' => 'Unemployed',
            'is_pwd' => true,
            'active' => true,
        ]);

        // Poor Health Status - Lower Middle Income
        Residents::create([
            'first_name' => 'Lourdes',
            'middle_name' => 'Fernandez',
            'last_name' => 'Castro',
            'suffix' => null,
            'email' => 'lourdes.fernandez@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 1, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09191234595',
            'birth_date' => Carbon::now()->subYears(50),
            'marital_status' => 'Married',
            'occupation' => 'Vendor',
            'age' => 50,
            'family_size' => 5,
            'education_level' => 'Elementary',
            'income_level' => 'Lower Middle',
            'employment_status' => 'Self-employed',
            'is_pwd' => true,
            'active' => true,
        ]);
        Residents::create([
            'first_name' => 'Kyo',
            'middle_name' => null,
            'last_name' => 'Kusanagi',
            'suffix' => null,
            'email' => 'kyo.kusanagi@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 1, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => '09123456789',
            'birth_date' => Carbon::now()->subYears(50),
            'marital_status' => 'Married',
            'occupation' => 'Vendor',
            'age' => 50,
            'family_size' => 5,
            'education_level' => 'Elementary',
            'income_level' => 'Lower Middle',
            'employment_status' => 'Self-employed',
            'is_pwd' => true,
            'active' => true,
        ]);

        // Resident without email (for testing account request linking)
        Residents::create([
            'first_name' => 'Maria',
            'middle_name' => 'Concepcion',
            'last_name' => 'Villanueva',
            'suffix' => null,
            'email' => null,
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 2, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => null,
            'birth_date' => Carbon::now()->subYears(45),
            'marital_status' => 'Married',
            'occupation' => 'Housewife',
            'age' => 45,
            'family_size' => 4,
            'education_level' => 'High School',
            'income_level' => 'Lower Middle',
            'employment_status' => 'Unemployed',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Resident without contact number
        Residents::create([
            'first_name' => 'Ricardo',
            'middle_name' => 'Manuel',
            'last_name' => 'Bautista',
            'suffix' => null,
            'email' => 'ricardo.bautista@email.com',
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 3, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => null,
            'birth_date' => Carbon::now()->subYears(52),
            'marital_status' => 'Married',
            'occupation' => 'Farmer',
            'age' => 52,
            'family_size' => 5,
            'education_level' => 'Elementary',
            'income_level' => 'Low',
            'employment_status' => 'Self-employed',
            'is_pwd' => 0,
            'active' => true,
        ]);

        // Resident without both email and contact number (for profiling only)
        Residents::create([
            'first_name' => 'Elena',
            'middle_name' => 'Rosa',
            'last_name' => 'Fernandez',
            'suffix' => null,
            'email' => null,
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 4, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Female',
            'contact_number' => null,
            'birth_date' => Carbon::now()->subYears(67),
            'marital_status' => 'Widowed',
            'occupation' => 'Housewife',
            'age' => 67,
            'family_size' => 2,
            'education_level' => 'No Education',
            'income_level' => 'Low',
            'employment_status' => 'Unemployed',
            'is_pwd' => true,
            'active' => true,
        ]);

        // Resident without email (another example for account request testing)
        Residents::create([
            'first_name' => 'Antonio',
            'middle_name' => 'Cruz',
            'last_name' => 'Ramos',
            'suffix' => 'Jr.',
            'email' => null,
            'password' => bcrypt('password123'),
            'role' => 'resident',
            'address' => 'Purok 5, Lower Malinao, Padada, Davao Del Sur',
            'gender' => 'Male',
            'contact_number' => null,
            'birth_date' => Carbon::now()->subYears(33),
            'marital_status' => 'Single',
            'occupation' => 'Driver',
            'age' => 33,
            'family_size' => 3,
            'education_level' => 'High School',
            'income_level' => 'Lower Middle',
            'employment_status' => 'Full-time',
            'is_pwd' => 0,
            'active' => true,
        ]);
    }
}
