<!DOCTYPE html>
<html>
<head>
    <title>{{ $documentRequest->document_type }} Request - {{ $documentRequest->id }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            font-size: 14px;
            color: #666;
        }
        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .details-table th, .details-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .details-table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .description {
            margin-top: 20px;
            border: 1px solid #eee;
            padding: 15px;
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 50px;
            text-align: right;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>BARANGAY DOCUMENT REQUEST</h1>
        <p>Barangay [Your Barangay Name Here]</p>
        <p>Date Generated: {{ \Carbon\Carbon::now()->format('F d, Y') }}</p>
    </div>

    <table class="details-table">
        <tr>
            <th>Request ID:</th>
            <td>{{ $documentRequest->id }}</td>
        </tr>
        <tr>
            <th>Document Type:</th>
            <td>{{ $documentRequest->document_type }}</td>
        </tr>
        <tr>
            <th>Request Status:</th>
            <td>{{ ucfirst($documentRequest->status) }}</td>
        </tr>
        <tr>
            <th>Requested By:</th>
            <td>{{ $documentRequest->user->name ?? 'N/A' }} ({{ $documentRequest->user->email ?? 'N/A' }})</td>
        </tr>
        <tr>
            <th>Date Filed:</th>
            <td>{{ \Carbon\Carbon::parse($documentRequest->created_at)->format('F d, Y h:i A') }}</td>
        </tr>
    </table>

    <div class="description">
        <h3>Purpose/Description:</h3>
        <p>{{ $documentRequest->description }}</p>
    </div>

    <div class="footer">
        <p>Generated by the Barangay Management System</p>
    </div>
</body>
</html>